name: Run Go Tests on Changed Directories

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Determine Changed Directories
        id: changes
        run: |
          # Check if this is the first commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "This is the first commit."
            echo "changed_dirs=$(git ls-tree --name-only HEAD | xargs -I {} dirname {} | sort | uniq)" >> $GITHUB_ENV
          else
            echo "changed_dirs=$(git diff --name-only HEAD~1 HEAD | xargs -I {} dirname {} | sort | uniq)" >> $GITHUB_ENV
          fi

      - name: Run Tests
        run: |
          for dir in ${{ env.changed_dirs }}; do
            if [ -d "$dir" ]; then
              echo "Running tests in $dir"
              (cd "$dir" && go test ./...)
            fi
          done
