name: Run Go Tests on Changed Directories

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Determine Changed Directories
        id: changes
        run: |
          # Check if this is the first commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "This is the first commit."
            changed_dirs=$(git ls-tree --name-only -d HEAD)
          else
            changed_dirs=$(git diff --name-only HEAD~1 HEAD | xargs -I {} dirname {} | sort | uniq)
          fi

          # Filter out directories containing '_template'
          filtered_dirs=$(echo "$changed_dirs" | grep -v '_template')
          filtered_dirs=$(echo "$changed_dirs" | grep -v '.github')
          # Print the directories to be tested
          echo "Directories to be tested: $filtered_dirs"

          # Escape directory names for use in environment variables
          escaped_dirs=$(echo $filtered_dirs | sed 's/ /%20/g')
          echo "escaped_dirs=$escaped_dirs" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          # Decode the escaped directory names
          decoded_dirs=$(echo ${{ env.escaped_dirs }} | sed 's/%20/ /g')
          for dir in $decoded_dirs; do
            if [ -d "$dir" ]; then
              echo "Running tests in $dir"
              (cd "$dir" && go test -v ./...)
            fi
          done
